---

- name: get current promtail version
  ansible.builtin.command: /usr/local/bin/promtail -version
  register: promtail_current
  ignore_errors: yes
  changed_when: no

- ansible.builtin.import_tasks: install.yml
  when: promtail_current.rc != 0 or not promtail_current.stdout is search(promtail_version_string_match)
