---

- name: get current promtail version
  ansible.builtin.command: /usr/local/bin/promtail -version
  register: promtail_current
  ignore_errors: yes
  changed_when: no

- name: import install.yml
  ansible.builtin.import_tasks: install.yml
  when: promtail_current.rc != 0 or not promtail_current.stdout is search(promtail_version_string_match)

- name: import config.yml
  ansible.builtin.import_tasks: config.yml

- name: import systemd.yml
  ansible.builtin.import_tasks: systemd.yml
